# Generated by Django 2.2.4 on 2020-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safravoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqbuilder',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='client_id'),
        ),
    ]
